{
    "name": "ClickUp Integration",
    "version": "1.0",
    "technical_name": "clickup_integration",
    "author": "Mohtashim",
    "category": "Tools",
    "summary": "Integrate ClickUp OAuth2 with Odoo",
    "depends": ["base", 'web','project'],
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        "views/clickup_views.xml",
        "views/clickup_team_views.xml",
        "views/res_users_view.xml",
        'views/clickup_authorization_view.xml',
        'views/clickup_task_views.xml',
        'views/clickup_space_view.xml',
        'views/clickup_list_views.xml',
        'views/clickup_folder_view.xml',
    ],
    "installable": True,
    "application": True,
}
